const bookingTypes = {
  SUBMIT_CANCEL_BOOKING_REQUEST: "SUBMIT_CANCEL_BOOKING_REQUEST",
  SUBMIT_CANCEL_BOOKING_SUCCESS: "SUBMIT_CANCEL_BOOKING_SUCCESS",
  SUBMIT_CANCEL_BOOKING_FAIL: "SUBMIT_CANCEL_BOOKING_FAIL",
};

export default bookingTypes;
