const ratingTypes = {
  GET_RATINGS_RECEIVED_PASSENGER_REQUEST:
    "GET_RATINGS_RECEIVED_PASSENGER_REQUEST",
  GET_RATINGS_RECEIVED_PASSENGER_SUCCESS:
    "GET_RATINGS_RECEIVED_PASSENGER_SUCCESS",
  GET_RATINGS_RECEIVED_PASSENGER_FAIL: "GET_RATINGS_RECEIVED_PASSENGER_FAIL",

  GET_RATINGS_GIVEN_PASSENGER_REQUEST: "GET_RATINGS_GIVEN_PASSENGER_REQUEST",
  GET_RATINGS_GIVEN_PASSENGER_SUCCESS: "GET_RATINGS_GIVEN_PASSENGER_SUCCESS",
  GET_RATINGS_GIVEN_PASSENGER_FAIL: "GET_RATINGS_GIVEN_PASSENGER_FAIL",

  GET_RATINGS_RECEIVED_DRIVER_REQUEST: "GET_RATINGS_RECEIVED_DRIVER_REQUEST",
  GET_RATINGS_RECEIVED_DRIVER_SUCCESS: "GET_RATINGS_RECEIVED_DRIVER_SUCCESS",
  GET_RATINGS_RECEIVED_DRIVER_FAIL: "GET_RATINGS_RECEIVED_DRIVER_FAIL",

  GET_RATINGS_GIVEN_DRIVER_REQUEST: "GET_RATINGS_GIVEN_DRIVER_REQUEST",
  GET_RATINGS_GIVEN_DRIVER_SUCCESS: "GET_RATINGS_GIVEN_DRIVER_SUCCESS",
  GET_RATINGS_GIVEN_DRIVER_FAIL: "GET_RATINGS_GIVEN_DRIVER_FAIL",

  GET_RATINGS_TO_DO_PASSENGER_REQUEST: "GET_RATINGS_TO_DO_PASSENGER_REQUEST",
  GET_RATINGS_TO_DO_PASSENGER_SUCCESS: "GET_RATINGS_TO_DO_PASSENGER_SUCCESS",
  GET_RATINGS_TO_DO_PASSENGER_FAIL: "GET_RATINGS_TO_DO_PASSENGER_FAIL",

  GET_RATINGS_TO_DO_DRIVER_REQUEST: "GET_RATINGS_TO_DO_DRIVER_REQUEST",
  GET_RATINGS_TO_DO_DRIVER_SUCCESS: "GET_RATINGS_TO_DO_DRIVER_SUCCESS",
  GET_RATINGS_TO_DO_DRIVER_FAIL: "GET_RATINGS_TO_DO_DRIVER_FAIL",

  SUBMIT_PASSENGER_RATING_FORM_REQUEST: "SUBMIT_PASSENGER_RATING_FORM_REQUEST",
  SUBMIT_PASSENGER_RATING_FORM_SUCCESS: "SUBMIT_PASSENGER_RATING_FORM_SUCCESS",
  SUBMIT_PASSENGER_RATING_FORM_FAIL: "SUBMIT_PASSENGER_RATING_FORM_FAIL",

  SUBMIT_DRIVER_RATING_FORM_REQUEST: "SUBMIT_DRIVER_RATING_FORM_REQUEST",
  SUBMIT_DRIVER_RATING_FORM_SUCCESS: "SUBMIT_DRIVER_RATING_FORM_SUCCESS",
  SUBMIT_DRIVER_RATING_FORM_FAIL: "SUBMIT_DRIVER_RATING_FORM_FAIL",

  GET_DRIVER_RATINGS_REQUEST: "GET_DRIVER_RATINGS_REQUEST",
  GET_DRIVER_RATINGS_SUCCESS: "GET_DRIVER_RATINGS_SUCCESS",
  GET_DRIVER_RATINGS_FAIL: "GET_DRIVER_RATINGS_FAIL",

  GET_PASSENGER_RATINGS_REQUEST: "GET_PASSENGER_RATINGS_REQUEST",
  GET_PASSENGER_RATINGS_SUCCESS: "GET_PASSENGER_RATINGS_SUCCESS",
  GET_PASSENGER_RATINGS_FAIL: "GET_PASSENGER_RATINGS_FAIL",
};

export default ratingTypes;
