const rideTypes = {
  GET_USER_RIDES_REQUEST: "GET_USER_RIDES_REQUEST",
  GET_USER_RIDES_SUCCESS: "GET_USER_RIDES_SUCCESS",
  GET_USER_RIDES_FAIL: "GET_USER_RIDES_FAIL",

  SUBMIT_FORM_OFFER_RIDE_REQUEST: "SUBMIT_FORM_OFFER_RIDE_REQUEST",
  SUBMIT_FORM_OFFER_RIDE_SUCCESS: "SUBMIT_FORM_OFFER_RIDE_SUCCESS",
  SUBMIT_FORM_OFFER_RIDE_FAIL: "SUBMIT_FORM_OFFER_RIDE_FAIL",

  GET_RIDE_REQUEST: "GET_RIDE_REQUEST",
  GET_RIDE_SUCCESS: "GET_RIDE_SUCCESS",
  GET_RIDE_FAIL: "GET_RIDE_FAIL",

  GET_BOOKING_REQUEST: "GET_BOOKING_REQUEST",
  GET_BOOKING_SUCCESS: "GET_BOOKING_SUCCESS",
  GET_BOOKING_FAIL: "GET_BOOKING_FAIL",

  GET_DRIVER_BOOKINGS_REQUEST: "GET_DRIVER_BOOKINGS_REQUEST",
  GET_DRIVER_BOOKINGS_SUCCESS: "GET_DRIVER_BOOKINGS_SUCCESS",
  GET_DRIVER_BOOKINGS_FAIL: "GET_DRIVER_BOOKINGS_FAIL",

  GET_ALL_RIDES_REQUEST: "GET_ALL_RIDES_REQUEST",
  GET_ALL_RIDES_SUCCESS: "GET_ALL_RIDES_SUCCESS",
  GET_ALL_RIDES_FAIL: "GET_ALL_RIDES_FAIL",

  GET_USER_RIDE_BOOKING_REQUEST: "GET_USER_RIDE_BOOKING_REQUEST",
  GET_USER_RIDE_BOOKING_SUCCESS: "GET_USER_RIDE_BOOKING_SUCCESS",
  GET_USER_RIDE_BOOKING_FAIL: "GET_USER_RIDE_BOOKING_FAIL",

  GET_DRIVER_RIDE_BOOKING_REQUEST: "GET_DRIVER_RIDE_BOOKING_REQUEST",
  GET_DRIVER_RIDE_BOOKING_SUCCESS: "GET_DRIVER_RIDE_BOOKING_SUCCESS",
  GET_DRIVER_RIDE_BOOKING_FAIL: "GET_DRIVER_RIDE_BOOKING_FAIL",

  SUBMIT_FORM_BOOK_RIDE_REQUEST: "SUBMIT_FORM_BOOK_RIDE_REQUEST",
  SUBMIT_FORM_BOOK_RIDE_SUCCESS: "SUBMIT_FORM_BOOK_RIDE_SUCCESS",
  SUBMIT_FORM_BOOK_RIDE_FAIL: "SUBMIT_FORM_BOOK_RIDE_FAIL",

  SUBMIT_FORM_DRIVER_RESPONSE_BOOKING_REQUEST:
    "SUBMIT_FORM_DRIVER_RESPONSE_BOOKING_REQUEST",
  SUBMIT_FORM_DRIVER_RESPONSE_BOOKING_SUCCESS:
    "SUBMIT_FORM_DRIVER_RESPONSE_BOOKING_SUCCESS",
  SUBMIT_FORM_DRIVER_RESPONSE_BOOKING_FAIL:
    "SUBMIT_FORM_DRIVER_RESPONSE_BOOKING_FAIL",

  GET_USER_BOOKINGS_REQUEST: "GET_USER_BOOKINGS_REQUEST",
  GET_USER_BOOKINGS_SUCCESS: "GET_USER_BOOKINGS_SUCCESS",
  GET_USER_BOOKINGS_FAIL: "GET_USER_BOOKINGS_FAIL",

  GET_PASSENGERS_DETAILS_REQUEST: "GET_PASSENGERS_DETAILS_REQUEST",
  GET_PASSENGERS_DETAILS_SUCCESS: "GET_PASSENGERS_DETAILS_SUCCESS",
  GET_PASSENGERS_DETAILS_FAIL: "GET_PASSENGERS_DETAILS_FAIL",

  GET_RIDES_TO_CONFIRM_REQUEST: "GET_RIDES_TO_CONFIRM_REQUEST",
  GET_RIDES_TO_CONFIRM_SUCCESS: "GET_RIDES_TO_CONFIRM_SUCCESS",
  GET_RIDES_TO_CONFIRM_FAIL: "GET_RIDES_TO_CONFIRM_FAIL",

  SUBMIT_FORM_CONFIRM_RIDE_REQUEST: "SUBMIT_FORM_CONFIRM_RIDE_REQUEST",
  SUBMIT_FORM_CONFIRM_RIDE_SUCCESS: "SUBMIT_FORM_CONFIRM_RIDE_SUCCESS",
  SUBMIT_FORM_CONFIRM_RIDE_FAIL: "SUBMIT_FORM_CONFIRM_RIDE_FAIL",

  SUBMIT_FORM_FIND_RIDE_REQUESTED: "SUBMIT_FORM_FIND_RIDE_REQUESTED",
  RESET_FORM_FIND_RIDE: "RESET_FORM_FIND_RIDE",

  SET_SEARCH_ADDRESS: "SET_SEARCH_ADDRESS",
  SET_LOCATION: "SET_LOCATION",
  RESET_SEARCH: "RESET_SEARCH",

  SET_RIDE_ORIGIN: "SET_RIDE_ORIGIN",
  SET_RIDE_DESTINATION: "SET_RIDE_DESTINATION",
  SET_RIDE_DATE: "SET_RIDE_DATE",
  SET_RIDE_TIME: "SET_RIDE_TIME",
  SET_RIDE_SEATS: "SET_RIDE_SEATS",
  SET_RIDE_COMMENT: "SET_RIDE_COMMENT",
  RESET_FORM_OFFER_RIDE: "RESET_FORM_OFFER_RIDE",
};

export default rideTypes;
