const emailTypes = {
  CONFIRM_EMAIL_REQUEST: "CONFIRM_EMAIL_REQUEST",
  CONFIRM_EMAIL_SUCCESS: "CONFIRM_EMAIL_SUCCESS",
  CONFIRM_EMAIL_FAIL: "CONFIRM_EMAIL_FAIL",

  SEND_EMAIL_REQUEST: "SEND_EMAIL_REQUEST",
  SEND_EMAIL_SUCCESS: "SEND_EMAIL_SUCCESS",
  SEND_EMAIL_FAIL: "SEND_EMAIL_FAIL",

  OFFER_RIDE: "OFFER_RIDE",
  BOOK_RIDE_BY_USER: "BOOK_RIDE_BY_USER",
  BOOK_RIDE_TO_DRIVER: "BOOK_RIDE_TO_DRIVER",

  ACCEPTED_BY_DRIVER: "ACCEPTED_BY_DRIVER",
  ACCEPTED_TO_USER: "ACCEPTED_TO_USER",
  REFUSED_BY_DRIVER: "REFUSED_BY_DRIVER",
  REFUSED_TO_USER: "REFUSED_TO_USER",
};

export default emailTypes;
