"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Rides", [
      {
        DriverId: 1,
        cityOrigin: "Sámara",
        provinceOrigin: "Guanacaste",
        cityDestination: "San Salvador",
        provinceDestination: "San José",
        dateTime: new Date(new Date().setDate(new Date().getDate() + 5)),
        seatsAvailable: 2,
        seatsLeft: 2,
        comment: "Passing by Ruta 27 and San Jose",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        DriverId: 2,
        cityOrigin: "San Salvador",
        provinceOrigin: "Guanacaste",
        cityDestination: "Sámara",
        provinceDestination: "San José",
        dateTime: new Date(new Date().setDate(new Date().getDate() + 15)),
        seatsAvailable: 4,
        seatsLeft: 2,
        comment: "Diamante valley",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        DriverId: 2,
        cityOrigin: "Uvita",
        provinceOrigin: "San José",
        cityDestination: "San Salvador",
        provinceDestination: "Guanacaste",
        dateTime: new Date(new Date().setDate(new Date().getDate() + 50)),
        seatsAvailable: 4,
        seatsLeft: 4,
        comment: "My first ride",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        DriverId: 1,
        cityOrigin: "Dominical",
        provinceOrigin: "Puntarenas",
        cityDestination: "Puerto Viejo",
        provinceDestination: "Límon",
        dateTime: new Date(new Date().setDate(new Date().getDate() + 300)),
        seatsAvailable: 4,
        seatsLeft: 3,
        comment: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        DriverId: 1,
        cityOrigin: "San Salvador",
        provinceOrigin: "Guanacaste",
        cityDestination: "Sámara",
        provinceDestination: "San José",
        dateTime: new Date(new Date().setDate(new Date().getDate() + 150)),
        seatsAvailable: 4,
        seatsLeft: 4,
        comment: "I have a lot of seats available if you need",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        DriverId: 2,
        cityOrigin: "Samara",
        provinceOrigin: "Guanacaste",
        cityDestination: "Dominical",
        provinceDestination: "San José",
        dateTime: new Date(new Date().setDate(new Date().getDate() + 300)),
        seatsAvailable: 1,
        seatsLeft: 0,
        comment: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Rides", null, {});
  },
};
