const ratingTypes = {
  GET_RATINGS_RECEIVED_PASSENGER_REQUEST:
    "GET_RATINGS_RECEIVED_PASSENGER_REQUEST",
  GET_RATINGS_RECEIVED_PASSENGER_SUCCESS:
    "GET_RATINGS_RECEIVED_PASSENGER_SUCCESS",
  GET_RATINGS_RECEIVED_PASSENGER_FAIL: "GET_RATINGS_RECEIVED_PASSENGER_FAIL",

  GET_RATINGS_GIVEN_PASSENGER_REQUEST: "GET_RATINGS_GIVEN_PASSENGER_REQUEST",
  GET_RATINGS_GIVEN_PASSENGER_SUCCESS: "GET_RATINGS_GIVEN_PASSENGER_SUCCESS",
  GET_RATINGS_GIVEN_PASSENGER_FAIL: "GET_RATINGS_GIVEN_PASSENGER_FAIL",

  GET_RATINGS_RECEIVED_DRIVER_REQUEST: "GET_RATINGS_RECEIVED_DRIVER_REQUEST",
  GET_RATINGS_RECEIVED_DRIVER_SUCCESS: "GET_RATINGS_RECEIVED_DRIVER_SUCCESS",
  GET_RATINGS_RECEIVED_DRIVER_FAIL: "GET_RATINGS_RECEIVED_DRIVER_FAIL",

  GET_RATINGS_GIVEN_DRIVER_REQUEST: "GET_RATINGS_GIVEN_DRIVER_REQUEST",
  GET_RATINGS_GIVEN_DRIVER_SUCCESS: "GET_RATINGS_GIVEN_DRIVER_SUCCESS",
  GET_RATINGS_GIVEN_DRIVER_FAIL: "GET_RATINGS_GIVEN_DRIVER_FAIL",
};

export default ratingTypes;
