const GET_USER_RIDES_REQUEST = "GET_USER_RIDES_REQUEST";
const GET_USER_RIDES_SUCCESS = "GET_USER_RIDES_SUCCESS";
const GET_USER_RIDES_FAIL = "GET_USER_RIDES_FAIL";

const SUBMIT_FORM_OFFER_RIDE_REQUEST = "SUBMIT_FORM_OFFER_RIDE_REQUEST";
const SUBMIT_FORM_OFFER_RIDE_SUCCESS = "SUBMIT_FORM_OFFER_RIDE_SUCCESS";
const SUBMIT_FORM_OFFER_RIDE_FAIL = "SUBMIT_FORM_OFFER_RIDE_FAIL";

const GET_ALL_RIDES_REQUEST = "GET_ALL_RIDES_REQUEST";
const GET_ALL_RIDES_SUCCESS = "GET_ALL_RIDES_SUCCESS";
const GET_ALL_RIDES_FAIL = "GET_ALL_RIDES_FAIL";

const rideTypes = {
  GET_USER_RIDES_REQUEST,
  GET_USER_RIDES_SUCCESS,
  GET_USER_RIDES_FAIL,
  SUBMIT_FORM_OFFER_RIDE_REQUEST,
  SUBMIT_FORM_OFFER_RIDE_SUCCESS,
  SUBMIT_FORM_OFFER_RIDE_FAIL,
  GET_ALL_RIDES_REQUEST,
  GET_ALL_RIDES_SUCCESS,
  GET_ALL_RIDES_FAIL,
};

export default rideTypes;
