const GET_USER_RIDES_REQUEST = "GET_USER_RIDES_REQUEST";
const GET_USER_RIDES_SUCCESS = "GET_USER_RIDES_SUCCESS";
const GET_USER_RIDES_FAIL = "GET_USER_RIDES_FAIL";

const SUBMIT_FORM_OFFER_RIDE_REQUEST = "SUBMIT_FORM_OFFER_RIDE_REQUEST";
const SUBMIT_FORM_OFFER_RIDE_SUCCESS = "SUBMIT_FORM_OFFER_RIDE_SUCCESS";
const SUBMIT_FORM_OFFER_RIDE_FAIL = "SUBMIT_FORM_OFFER_RIDE_FAIL";

const GET_RIDE_REQUEST = "GET_RIDE_REQUEST";
const GET_RIDE_SUCCESS = "GET_RIDE_SUCCESS";
const GET_RIDE_FAIL = "GET_RIDE_FAIL";

const GET_ALL_RIDES_REQUEST = "GET_ALL_RIDES_REQUEST";
const GET_ALL_RIDES_SUCCESS = "GET_ALL_RIDES_SUCCESS";
const GET_ALL_RIDES_FAIL = "GET_ALL_RIDES_FAIL";

const GET_USER_RIDE_BOOKING_REQUEST = "GET_USER_RIDE_BOOKING_REQUEST";
const GET_USER_RIDE_BOOKING_SUCCESS = "GET_USER_RIDE_BOOKING_SUCCESS";
const GET_USER_RIDE_BOOKING_FAIL = "GET_USER_RIDE_BOOKING_FAIL";

const SUBMIT_FORM_BOOK_RIDE_REQUEST = "SUBMIT_FORM_BOOK_RIDE_REQUEST";
const SUBMIT_FORM_BOOK_RIDE_SUCCESS = "SUBMIT_FORM_BOOK_RIDE_SUCCESS";
const SUBMIT_FORM_BOOK_RIDE_FAIL = "SUBMIT_FORM_BOOK_RIDE_FAIL";

const GET_DRIVER_RIDES_REQUESTS_REQUEST = "GET_DRIVER_RIDES_REQUESTS_REQUEST";
const GET_DRIVER_RIDES_REQUESTS_SUCCESS = "GET_DRIVER_RIDES_REQUESTS_SUCCESS";
const GET_DRIVER_RIDES_REQUESTS_FAIL = "GET_DRIVER_RIDES_REQUESTS_FAIL";

const rideTypes = {
  GET_USER_RIDES_REQUEST,
  GET_USER_RIDES_SUCCESS,
  GET_USER_RIDES_FAIL,

  SUBMIT_FORM_OFFER_RIDE_REQUEST,
  SUBMIT_FORM_OFFER_RIDE_SUCCESS,
  SUBMIT_FORM_OFFER_RIDE_FAIL,

  GET_RIDE_REQUEST,
  GET_RIDE_SUCCESS,
  GET_RIDE_FAIL,

  GET_ALL_RIDES_REQUEST,
  GET_ALL_RIDES_SUCCESS,
  GET_ALL_RIDES_FAIL,

  SUBMIT_FORM_BOOK_RIDE_REQUEST,
  SUBMIT_FORM_BOOK_RIDE_SUCCESS,
  SUBMIT_FORM_BOOK_RIDE_FAIL,

  GET_USER_RIDE_BOOKING_REQUEST,
  GET_USER_RIDE_BOOKING_SUCCESS,
  GET_USER_RIDE_BOOKING_FAIL,

  GET_DRIVER_RIDES_REQUESTS_REQUEST,
  GET_DRIVER_RIDES_REQUESTS_SUCCESS,
  GET_DRIVER_RIDES_REQUESTS_FAIL,
};

export default rideTypes;
