const adminTypes = {
  ADMIN_GET_USERS_REQUEST: "ADMIN_GET_USERS_REQUEST",
  ADMIN_GET_USERS_SUCCESS: "ADMIN_GET_USERS_SUCCESS",
  ADMIN_GET_USERS_FAIL: "ADMIN_GET_USERS_FAIL",

  ADMIN_GET_USERS_CONVERSATIONS_REQUEST:
    "ADMIN_GET_USERS_CONVERSATIONS_REQUEST",
  ADMIN_GET_USERS_CONVERSATIONS_SUCCESS:
    "ADMIN_GET_USERS_CONVERSATIONS_SUCCESS",
  ADMIN_GET_USERS_CONVERSATIONS_FAIL: "ADMIN_GET_USERS_CONVERSATIONS_FAIL",

  ADMIN_GET_SINGLE_CONVERSATION_REQUEST:
    "ADMIN_GET_SINGLE_CONVERSATION_REQUEST",
  ADMIN_GET_SINGLE_CONVERSATION_SUCCESS:
    "ADMIN_GET_SINGLE_CONVERSATION_SUCCESS",
  ADMIN_GET_SINGLE_CONVERSATION_FAIL: "ADMIN_GET_SINGLE_CONVERSATION_FAIL",

  ADMIN_GET_RIDES_REQUEST: "ADMIN_GET_RIDES_REQUEST",
  ADMIN_GET_RIDES_SUCCESS: "ADMIN_GET_RIDES_SUCCESS",
  ADMIN_GET_RIDES_FAIL: "ADMIN_GET_RIDES_FAIL",

  ADMIN_GET_SINGLE_RIDE_REQUEST: "ADMIN_GET_SINGLE_RIDE_REQUEST",
  ADMIN_GET_SINGLE_RIDE_SUCCESS: "ADMIN_GET_SINGLE_RIDE_SUCCESS",
  ADMIN_GET_SINGLE_RIDE_FAIL: "ADMIN_GET_SINGLE_RIDE_FAIL",

  ADMIN_GET_SINGLE_RIDE_ALL_BOOKINGS_REQUEST:
    "ADMIN_GET_SINGLE_RIDE_ALL_BOOKINGS_REQUEST",
  ADMIN_GET_SINGLE_RIDE_ALL_BOOKINGS_SUCCESS:
    "ADMIN_GET_SINGLE_RIDE_ALL_BOOKINGS_SUCCESS",
  ADMIN_GET_SINGLE_RIDE_ALL_BOOKINGS_FAIL:
    "ADMIN_GET_SINGLE_RIDE_ALL_BOOKINGS_FAIL",

  ADMIN_SEND_TEST_EMAIL_REQUEST: "ADMIN_SEND_TEST_EMAIL_REQUEST",
  ADMIN_SEND_TEST_EMAIL_SUCCESS: "ADMIN_SEND_TEST_EMAIL_SUCCESS",
  ADMIN_SEND_TEST_EMAIL_FAIL: "ADMIN_SEND_TEST_EMAIL_FAIL",
};

export default adminTypes;
