const adminTypes = {
  ADMIN_GET_USERS_REQUEST: "ADMIN_GET_USERS_REQUEST",
  ADMIN_GET_USERS_SUCCESS: "ADMIN_GET_USERS_SUCCESS",
  ADMIN_GET_USERS_FAIL: "ADMIN_GET_USERS_FAIL",

  ADMIN_GET_USERS_CONVERSATIONS_REQUEST:
    "ADMIN_GET_USERS_CONVERSATIONS_REQUEST",
  ADMIN_GET_USERS_CONVERSATIONS_SUCCESS:
    "ADMIN_GET_USERS_CONVERSATIONS_SUCCESS",
  ADMIN_GET_USERS_CONVERSATIONS_FAIL: "ADMIN_GET_USERS_CONVERSATIONS_FAIL",
};

export default adminTypes;
