const SET_GLOBAL_STATE = "SET_GLOBAL_STATE";

const globalTypes = {
  SET_GLOBAL_STATE,
  SET_FEEDBACK_NOTIFICATION: "SET_FEEDBACK_NOTIFICATION",
  CLEAR_FEEDBACK_NOTIFICATION: "CLEAR_FEEDBACK_NOTIFICATION",
};

export default globalTypes;
