const SET_SUPPORTED_LANGUAGES_CODES = "SET_SUPPORTED_LANGUAGES_CODES";
const SET_SUPPORTED_LANGUAGES_NAMES = "SET_SUPPORTED_LANGUAGES_NAMES";

const globalTypes = {
  SET_SUPPORTED_LANGUAGES_CODES,
  SET_SUPPORTED_LANGUAGES_NAMES,
};

export default globalTypes;
