const CHANGE_FORM_EMAIL = "CHANGE_FORM_EMAIL";
const CHANGE_FORM_FIRSTNAME = "CHANGE_FORM_FIRSTNAME";
const CHANGE_FORM_LASTNAME = "CHANGE_FORM_LASTNAME";
const CHANGE_FORM_USERNAME = "CHANGE_FORM_USERNAME";
const CHANGE_FORM_DATEOFBIRTH = "CHANGE_FORM_DATEOFBIRTH";
const CHANGE_FORM_LANGUAGE = "CHANGE_FORM_LANGUAGE";
const CHANGE_FORM_PHONENUMBER = "CHANGE_FORM_PHONENUMBER";

const CHECK_DUPLICATE_USERNAME_REQUESTED = "CHECK_DUPLICATE_USERNAME_REQUESTED";
const CHECK_DUPLICATE_USERNAME_SUCCESS = "CHECK_DUPLICATE_USERNAME_SUCCESS";
const CHECK_DUPLICATE_USERNAME_FAIL = "CHECK_DUPLICATE_USERNAME_FAIL";

const CHECK_DUPLICATE_EMAIL_REQUESTED = "CHECK_DUPLICATE_EMAIL_REQUESTED";
const CHECK_DUPLICATE_EMAIL_SUCCESS = "CHECK_DUPLICATE_EMAIL_SUCCESS";
const CHECK_DUPLICATE_EMAIL_FAIL = "CHECK_DUPLICATE_EMAIL_FAIL";

const CHECK_DUPLICATE_PHONENUMBER_REQUESTED =
  "CHECK_DUPLICATE_PHONENUMBER_REQUESTED";
const CHECK_DUPLICATE_PHONENUMBER_SUCCESS =
  "CHECK_DUPLICATE_PHONENUMBER_SUCCESS";
const CHECK_DUPLICATE_PHONENUMBER_FAIL = "CHECK_DUPLICATE_PHONENUMBER_FAIL";

const signupTypes = {
  CHANGE_FORM_EMAIL,
  CHANGE_FORM_FIRSTNAME,
  CHANGE_FORM_LASTNAME,
  CHANGE_FORM_USERNAME,
  CHANGE_FORM_DATEOFBIRTH,
  CHANGE_FORM_LANGUAGE,
  CHANGE_FORM_PHONENUMBER,
  CHECK_DUPLICATE_USERNAME_REQUESTED,
  CHECK_DUPLICATE_USERNAME_SUCCESS,
  CHECK_DUPLICATE_USERNAME_FAIL,
  CHECK_DUPLICATE_EMAIL_REQUESTED,
  CHECK_DUPLICATE_EMAIL_SUCCESS,
  CHECK_DUPLICATE_EMAIL_FAIL,
  CHECK_DUPLICATE_PHONENUMBER_REQUESTED,
  CHECK_DUPLICATE_PHONENUMBER_SUCCESS,
  CHECK_DUPLICATE_PHONENUMBER_FAIL,
};

export default signupTypes;
