const GET_DRIVER_NEW_RIDES_REQUESTS_REQUEST =
  "GET_DRIVER_NEW_RIDES_REQUESTS_REQUEST";
const GET_DRIVER_NEW_RIDES_REQUESTS_SUCCESS =
  "GET_DRIVER_NEW_RIDES_REQUESTS_SUCCESS";
const GET_DRIVER_NEW_RIDES_REQUESTS_FAIL = "GET_DRIVER_NEW_RIDES_REQUESTS_FAIL";

const GET_DRIVER_RIDES_REQUESTS_REQUEST = "GET_DRIVER_RIDES_REQUESTS_REQUEST";
const GET_DRIVER_RIDES_REQUESTS_SUCCESS = "GET_DRIVER_RIDES_REQUESTS_SUCCESS";
const GET_DRIVER_RIDES_REQUESTS_FAIL = "GET_DRIVER_RIDES_REQUESTS_FAIL";

const messageTypes = {
  GET_DRIVER_NEW_RIDES_REQUESTS_REQUEST,
  GET_DRIVER_NEW_RIDES_REQUESTS_SUCCESS,
  GET_DRIVER_NEW_RIDES_REQUESTS_FAIL,

  GET_DRIVER_RIDES_REQUESTS_REQUEST,
  GET_DRIVER_RIDES_REQUESTS_SUCCESS,
  GET_DRIVER_RIDES_REQUESTS_FAIL,
};

export default messageTypes;
