const globalTypes = {
  GET_ALL_USER_MESSAGES_REQUEST: "GET_ALL_USER_MESSAGES_REQUEST",
  GET_ALL_USER_MESSAGES_SUCCESS: "GET_ALL_USER_MESSAGES_SUCCESS",
  GET_ALL_USER_MESSAGES_FAIL: "GET_ALL_USER_MESSAGES_FAIL",

  START_CONVERSATION_REQUEST: "START_CONVERSATION_REQUEST",
  START_CONVERSATION_SUCCESS: "START_CONVERSATION_SUCCESS",
  START_CONVERSATION_FAIL: "START_CONVERSATION_FAIL",

  CHANGE_CONVERSATION_VIEW: "CHANGE_CONVERSATION_VIEW",
  RESET_CONVERSATION_VIEW: "RESET_CONVERSATION_VIEW",
};

export default globalTypes;
