const userTypes = {
  REGISTER_USER_REQUESTED: "REGISTER_USER_REQUESTED",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAIL: "REGISTER_USER_FAIL",
  LOGIN_REQUESTED: "LOGIN_REQUESTED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",

  CONFIRM_EMAIL_REQUEST: "CONFIRM_EMAIL_REQUEST",
  CONFIRM_EMAIL_SUCCESS: "CONFIRM_EMAIL_SUCCESS",
  CONFIRM_EMAIL_FAIL: "CONFIRM_EMAIL_FAIL",

  SEND_EMAIL_FORGOT_PASSWORD_REQUESTED: "SEND_EMAIL_FORGOT_PASSWORD_REQUESTED",
  SEND_EMAIL_FORGOT_PASSWORD_DATA: "SEND_EMAIL_FORGOT_PASSWORD_DATA",
  SEND_EMAIL_FORGOT_PASSWORD_ERROR: "SEND_EMAIL_FORGOT_PASSWORD_ERROR",

  RESET_PASSWORD_REQUESTED: "RESET_PASSWORD_REQUESTED",
  RESET_PASSWORD_DATA: "RESET_PASSWORD_DATA",
  RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR",

  CHECK_DEPRECATED_LINK_RESET_PASSWORD_REQUESTED:
    "CHECK_DEPRECATED_LINK_RESET_PASSWORD_REQUESTED",
  CHECK_DEPRECATED_LINK_RESET_PASSWORD_DATA:
    "CHECK_DEPRECATED_LINK_RESET_PASSWORD_DATA",
  CHECK_DEPRECATED_LINK_RESET_PASSWORD_ERROR:
    "CHECK_DEPRECATED_LINK_RESET_PASSWORD_ERROR",

  RESEND_CONFIRMATION_LINK_REQUESTED: "RESEND_CONFIRMATION_LINK_REQUESTED",
  RESEND_CONFIRMATION_LINK_DATA: "RESEND_CONFIRMATION_LINK_DATA",
  RESEND_CONFIRMATION_LINK_ERROR: "RESEND_CONFIRMATION_LINK_ERROR",
};

export default userTypes;
