const globalTypes = {
  SET_GLOBAL_STATE: "SET_GLOBAL_STATE",
  SET_FEEDBACK: "SET_FEEDBACK",
  CLEAR_FEEDBACK: "CLEAR_FEEDBACK",

  GET_COUNTRIES_REQUEST: "GET_COUNTRIES_REQUEST",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
  GET_COUNTRIES_FAIL: "GET_COUNTRIES_FAIL",
};

export default globalTypes;
