const globalTypes = {
  SET_GLOBAL_STATE: "SET_GLOBAL_STATE",
  DISPLAY_NAV_BAR: "DISPLAY_NAV_BAR",

  GET_COUNTRIES_REQUEST: "GET_COUNTRIES_REQUEST",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
  GET_COUNTRIES_FAIL: "GET_COUNTRIES_FAIL",

  GET_CONSTANTS_REQUEST: "GET_CONSTANTS_REQUEST",
  GET_CONSTANTS_SUCCESS: "GET_CONSTANTS_SUCCESS",
  GET_CONSTANTS_FAIL: "GET_CONSTANTS_FAIL",
};

export default globalTypes;
