const notificationTypes = {
  GET_DRIVER_NEW_RIDES_REQUESTS_REQUEST:
    "GET_DRIVER_NEW_RIDES_REQUESTS_REQUEST",
  GET_DRIVER_NEW_RIDES_REQUESTS_SUCCESS:
    "GET_DRIVER_NEW_RIDES_REQUESTS_SUCCESS",
  GET_DRIVER_NEW_RIDES_REQUESTS_FAIL: "GET_DRIVER_NEW_RIDES_REQUESTS_FAIL",

  GET_PASSENGER_BOOKINGS_RESPONSES_REQUEST:
    "GET_PASSENGER_BOOKINGS_RESPONSES_REQUEST",
  GET_PASSENGER_BOOKINGS_RESPONSES_SUCCESS:
    "GET_PASSENGER_BOOKINGS_RESPONSES_SUCCESS",
  GET_PASSENGER_BOOKINGS_RESPONSES_FAIL:
    "GET_PASSENGER_BOOKINGS_RESPONSES_FAIL",

  RESET_NOTIFICATIONS: "RESET_NOTIFICATIONS",
};

export default notificationTypes;
